compare,pivioting and melting

In [1]:
import pandas as pd

Compare

In [8]:
shop_7Sep={
    "Fruites":["Mango","Apple","Banana","Papaya"],
    "Prices":[100,150,60,30],
    "Quantity":[10,8,12,14]
}

stock_7Sep=pd.DataFrame(shop_7Sep)

shop_8Sep={
    "Fruites":["Mango","Apple","Banana","Papaya"],
    "Prices":[120,200,60,35],
    "Quantity":[15,6,24,17]
}

stock_8Sep=pd.DataFrame(shop_8Sep)

stock_7Sep.compare(stock_8Sep)
stock_7Sep.compare(stock_8Sep,align_axis=0)
stock_7Sep.compare(stock_8Sep,keep_shape=True)
stock_7Sep.compare(stock_8Sep,keep_equal=True)
stock_7Sep.compare(stock_8Sep,align_axis=0,keep_equal=True,keep_shape=True)

        Fruites  Prices  Quantity
0 self    Mango     100        10
  other   Mango     120        15
1 self    Apple     150         8
  other   Apple     200         6
2 self   Banana      60        12
  other  Banana      60        24
3 self   Papaya      30        14
  other  Papaya      35        17

Pivoting

In [12]:
monthly_sales={
    "product":["laptop","mobile","laptop","mobile","laptop","laptop"],
    "months":["jan","jan","feb","feb","mar","april"],
    "price":[95000,25000,67000,12000,65000,75000]
}
sales=pd.DataFrame(monthly_sales)
sales
sales.pivot_table(
    columns="months",
    index="product",
    values="price",
    aggfunc="sum"
)

months     april      feb      jan      mar
product
laptop   75000.0  67000.0  95000.0  65000.0
mobile       NaN  12000.0  25000.0      NaN

Melting

In [14]:
shop_sales={
    "product":["laptop","mobile","mouse"],
    "jan":[45000,14000,140],
    "feb":[55000,23000,250],
    "mar":[66000,45000,540]
}
sales_df=pd.DataFrame(shop_sales)
sales_df.melt(
    id_vars="product",
    var_name="month",
    value_name="price"
)

  product month  price
0  laptop   jan  45000
1  mobile   jan  14000
2   mouse   jan    140
3  laptop   feb  55000
4  mobile   feb  23000
5   mouse   feb    250
6  laptop   mar  66000
7  mobile   mar  45000
8   mouse   mar    540