In [ ]:
#---------------Task-----------------------
# Create a DataFrame containing the total expense of each category.
# What is the average transaction amount for each payment mode?
# Find the highest individual transaction in each category
# Show total, average, minimum and maximum transaction amount for each payment mode.

Create a DataFrame containing the total expense of each category.

In [1]:
import pandas as pd

In [5]:
exp=pd.read_excel("subdata_pandas/expense (1).xlsx")
exp

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257         Cash
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000         Card
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50         Cash
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          UPI
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000         Card
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

In [6]:
exp.groupby("Category")["Amount"].sum()

Category
Bills         18724
Clothes        2890
Essentials     4485
Food           3022
Grocery        1028
Name: Amount, dtype: int64

What is the average transaction amount for each payment mode?

In [8]:
exp.groupby("Payment Mode")["Amount"].mean()

Payment Mode
Card    5926.666667
Cash     494.400000
UPI      464.062500
Name: Amount, dtype: float64

Find the highest individual transaction in each category

In [10]:
exp.groupby("Category")["Amount"].max()

Category
Bills         16000
Clothes        1890
Essentials     1500
Food            890
Grocery         456
Name: Amount, dtype: int64

Show total, average, minimum and maximum transaction amount for each payment mode.

In [14]:
exp.groupby("Payment Mode")["Amount"].agg(["sum","mean","max","min"])

                sum         mean    max  min
Payment Mode
Card          17780  5926.666667  16000  780
Cash           4944   494.400000   1500   30
UPI            7425   464.062500   1890   10